// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: mozc_sidecar.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// SPDX-License-Identifier: MIT

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Private, process-local protocol between hazkey-server and the optional
/// Mozc converter helper. This is deliberately separate from public Protocol
/// v2 so the reducer remains the sole owner of IME/session semantics.
enum Hazkey_MozcSidecar_Operation: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0
  case convert // = 1
  case ping // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .convert
    case 2: self = .ping
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .convert: return 1
    case .ping: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Hazkey_MozcSidecar_Operation] = [
    .unspecified,
    .convert,
    .ping,
  ]

}

struct Hazkey_MozcSidecar_Request: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var protocolVersion: UInt32 = 0

  var requestID: UInt64 = 0

  var operation: Hazkey_MozcSidecar_Operation = .unspecified

  var reading: String = String()

  var targetKeySize: UInt32 = 0

  var maxCandidates: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Hazkey_MozcSidecar_Candidate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var value: String = String()

  var description_p: String = String()

  var consumedKeySize: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Hazkey_MozcSidecar_Response: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var protocolVersion: UInt32 = 0

  var requestID: UInt64 = 0

  var ok: Bool = false

  var errorMessage: String = String()

  var candidates: [Hazkey_MozcSidecar_Candidate] = []

  var segmentKeySize: UInt32 = 0

  var datasetSha256: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "hazkey.mozc_sidecar"

extension Hazkey_MozcSidecar_Operation: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "OPERATION_UNSPECIFIED"),
    1: .same(proto: "OPERATION_CONVERT"),
    2: .same(proto: "OPERATION_PING"),
  ]
}

extension Hazkey_MozcSidecar_Request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Request"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "protocol_version"),
    2: .standard(proto: "request_id"),
    3: .same(proto: "operation"),
    4: .same(proto: "reading"),
    5: .standard(proto: "target_key_size"),
    6: .standard(proto: "max_candidates"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.protocolVersion) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.operation) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.reading) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.targetKeySize) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.maxCandidates) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.protocolVersion != 0 {
      try visitor.visitSingularUInt32Field(value: self.protocolVersion, fieldNumber: 1)
    }
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 2)
    }
    if self.operation != .unspecified {
      try visitor.visitSingularEnumField(value: self.operation, fieldNumber: 3)
    }
    if !self.reading.isEmpty {
      try visitor.visitSingularStringField(value: self.reading, fieldNumber: 4)
    }
    if self.targetKeySize != 0 {
      try visitor.visitSingularUInt32Field(value: self.targetKeySize, fieldNumber: 5)
    }
    if self.maxCandidates != 0 {
      try visitor.visitSingularUInt32Field(value: self.maxCandidates, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_MozcSidecar_Request, rhs: Hazkey_MozcSidecar_Request) -> Bool {
    if lhs.protocolVersion != rhs.protocolVersion {return false}
    if lhs.requestID != rhs.requestID {return false}
    if lhs.operation != rhs.operation {return false}
    if lhs.reading != rhs.reading {return false}
    if lhs.targetKeySize != rhs.targetKeySize {return false}
    if lhs.maxCandidates != rhs.maxCandidates {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Hazkey_MozcSidecar_Candidate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Candidate"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "value"),
    2: .same(proto: "description"),
    3: .standard(proto: "consumed_key_size"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.value) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.description_p) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.consumedKeySize) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.value.isEmpty {
      try visitor.visitSingularStringField(value: self.value, fieldNumber: 1)
    }
    if !self.description_p.isEmpty {
      try visitor.visitSingularStringField(value: self.description_p, fieldNumber: 2)
    }
    if self.consumedKeySize != 0 {
      try visitor.visitSingularUInt32Field(value: self.consumedKeySize, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_MozcSidecar_Candidate, rhs: Hazkey_MozcSidecar_Candidate) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.description_p != rhs.description_p {return false}
    if lhs.consumedKeySize != rhs.consumedKeySize {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Hazkey_MozcSidecar_Response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Response"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "protocol_version"),
    2: .standard(proto: "request_id"),
    3: .same(proto: "ok"),
    4: .standard(proto: "error_message"),
    5: .same(proto: "candidates"),
    6: .standard(proto: "segment_key_size"),
    7: .standard(proto: "dataset_sha256"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.protocolVersion) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.requestID) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.ok) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.errorMessage) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.candidates) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.segmentKeySize) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.datasetSha256) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.protocolVersion != 0 {
      try visitor.visitSingularUInt32Field(value: self.protocolVersion, fieldNumber: 1)
    }
    if self.requestID != 0 {
      try visitor.visitSingularUInt64Field(value: self.requestID, fieldNumber: 2)
    }
    if self.ok != false {
      try visitor.visitSingularBoolField(value: self.ok, fieldNumber: 3)
    }
    if !self.errorMessage.isEmpty {
      try visitor.visitSingularStringField(value: self.errorMessage, fieldNumber: 4)
    }
    if !self.candidates.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.candidates, fieldNumber: 5)
    }
    if self.segmentKeySize != 0 {
      try visitor.visitSingularUInt32Field(value: self.segmentKeySize, fieldNumber: 6)
    }
    if !self.datasetSha256.isEmpty {
      try visitor.visitSingularStringField(value: self.datasetSha256, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Hazkey_MozcSidecar_Response, rhs: Hazkey_MozcSidecar_Response) -> Bool {
    if lhs.protocolVersion != rhs.protocolVersion {return false}
    if lhs.requestID != rhs.requestID {return false}
    if lhs.ok != rhs.ok {return false}
    if lhs.errorMessage != rhs.errorMessage {return false}
    if lhs.candidates != rhs.candidates {return false}
    if lhs.segmentKeySize != rhs.segmentKeySize {return false}
    if lhs.datasetSha256 != rhs.datasetSha256 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
