#ifndef HAZKEY_SESSION_CLIENT_H
#define HAZKEY_SESSION_CLIENT_H

#include <functional>
#include <cstdint>
#include <optional>
#include <string>
#include <utility>

#include "base.pb.h"
#include "hazkey_effect_ledger.h"
#include "hazkey_recovery_journal.h"

struct HazkeyClientContext {
    std::string program;
    std::string frontend;
    bool secureInput = false;
};

struct HazkeyClientContextTransition {
    bool contextChanged = false;
    bool enteredSecure = false;
    bool clearPreedit = false;
    bool reopenSession = false;
    bool allowSurroundingText = true;
};

struct HazkeyProtocolCapabilities {
    uint32_t protocolVersion = 1;
    uint64_t featureBits = 0;
    uint32_t maxSnapshotVersion = 0;
    bool recoverySupport = false;
    bool idempotentRequestSupport = false;

    bool supportsV2() const {
        return protocolVersion >= 2 && idempotentRequestSupport;
    }
};

HazkeyClientContextTransition evaluateHazkeyClientContextTransition(
    const HazkeyClientContext& previous, const HazkeyClientContext& next);

class HazkeyClientSession {
   public:
    using RecoveryHandler = std::function<void()>;

    explicit HazkeyClientSession(HazkeyClientContext context,
                                 RecoveryHandler recoveryHandler = {})
        : context_(std::move(context)),
          recoveryHandler_(std::move(recoveryHandler)) {}

    const HazkeyClientContext& context() const { return context_; }
    const std::string& id() const { return id_; }
    const HazkeyProtocolCapabilities& capabilities() const { return capabilities_; }
    uint64_t revision() const { return revision_; }
    void setRevision(uint64_t revision) { revision_ = revision; }

    bool shouldApplyEffect(uint64_t effectID) {
        return effectLedger_.claim(effectID);
    }

    void clearEffects() { effectLedger_.clear(); }
    bool hasRecoveryCheckpoint() const {
        return !recoveryCheckpoint_.empty();
    }
    bool hasFallbackComposition() const { return !fallbackComposition_.empty(); }
    std::size_t pendingActionCount() const { return journal_.pending().size(); }
    bool hasConfirmedSnapshot() const { return !journal_.lastSnapshot().empty(); }

   private:
    friend class HazkeySessionClient;

    HazkeyClientContext context_;
    std::string id_;
    HazkeyProtocolCapabilities capabilities_;
    uint64_t revision_ = 0;
    HazkeyEffectLedger effectLedger_;
    HazkeyRecoveryJournal journal_;
    std::string recoveryCheckpoint_;
    std::string fallbackComposition_;
    RecoveryHandler recoveryHandler_;
};

class HazkeySessionClient {
   public:
    using Transport = std::function<std::optional<hazkey::ResponseEnvelope>(
        const hazkey::RequestEnvelope&, bool)>;

    explicit HazkeySessionClient(
        Transport transport,
        Transport bestEffortTransport = {})
        : transport_(std::move(transport)),
          bestEffortTransport_(bestEffortTransport
                                   ? std::move(bestEffortTransport)
                                   : transport_) {}

    bool open(HazkeyClientSession& session, bool tryConnect = true);
    bool close(HazkeyClientSession& session, bool tryConnect = false);
    bool updateContext(HazkeyClientSession& session, HazkeyClientContext context);
    void abandonUnconfirmedInput(HazkeyClientSession& session);

    // Sends one semantic v2 action.  The request ID is generated by the
    // client when the caller leaves it empty; retrying the same envelope is
    // therefore safe for a server implementing the v2 cache contract.
    std::optional<hazkey::ResponseEnvelope> transactV2(
        HazkeyClientSession& session,
        hazkey::commands::HandleImeAction action,
        bool tryConnect = true);

    // Sends an opportunistic action without replaying or joining the recovery
    // journal. It uses only the currently open transport/session; a later
    // semantic key remains responsible for recovery.
    std::optional<hazkey::ResponseEnvelope> transactV2BestEffort(
        HazkeyClientSession& session,
        hazkey::commands::HandleImeAction action);

   private:
    std::optional<hazkey::ResponseEnvelope> executeV2(
        HazkeyClientSession& session,
        hazkey::commands::HandleImeAction action,
        bool tryConnect,
        bool allowSessionRecovery = true,
        bool bestEffort = false);
    bool replayPendingV2(HazkeyClientSession& session, bool tryConnect);

    Transport transport_;
    Transport bestEffortTransport_;
};

#endif  // HAZKEY_SESSION_CLIENT_H
